### PR TITLE
Add open in codepen button so people can test their builds faster.

### PR DESCRIPTION
**Pull request by ryanseddon**
Thought this would be cool to have. 

Adds a open in codepen button which posts the generated source so people can play around with their custom builds a lot faster.

screen shot 2015-03-14 at 7 21 49 pm

screen shot 2015-03-14 at 7 22 33 pm

cc @chriscoyier any objections if we do this?

### CODE REVIEW

**Comment by chriscoyier** [comment]
woah sweet. definitely no objections. let me know if I can help.

**Comment by paulirish** [comment]
i dig it

**Comment by SlexAxton** [comment]
I dig it more.

**Comment by ryanseddon** [comment]
Alright I'm just gonna merge this and tweet about and see what people think.

**Comment by stucox** [comment]
Nice!

(Late to the party)

**Pull request merged**
